export const APP_LOADED = 'APP_LOADED';
export const TUTORIAL_MODAL_OPENED = 'TUTORIAL_MODAL_OPENED';
export const TUTORIAL_MODAL_CLOSED = 'TUTORIAL_MODAL_CLOSED';
export const TUTORIAL_MODAL_SKIPED = 'TUTORIAL_MODAL_SKIPED';
export const TUTORIAL_STEPS_CHANGED = 'TUTORIAL_STEPS_CHANGED';
